[package]
name = "less"
version = "0.1.0"
edition = "2024"

[dependencies]
minus = { version = "5.6.1", features = ["dynamic_output", "search"] }
anyhow = { version = "1.0.95", features = ["backtrace"] }

[dev-dependencies]
tempfile = "3.17.1"
