[package]
name = "less"
version = "0.1.0"
edition = "2024"

[dependencies]
minus = { git = "https://github.com/AMythicDev/minus", features = [
  "dynamic_output",
  "search",
] }
anyhow = { version = "1.0.95", features = ["backtrace"] }
